name: food_recipe_app_nsbm
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.2.6 <4.0.0"

dependencies:
  animated_native_splash: ^1.3.0
  animated_splash_screen: ^1.3.0
  carousel_slider: ^4.2.1
  chewie: 1.5.0
  flutter:
    sdk: flutter
  iconsax: ^0.0.8
  video_player: ^2.8.2
  youtube_player_flutter: ^8.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/greenhome.png
    - assets/images/
